import { CartProduct } from '../types'

export const productsData: CartProduct[] = [
  { 
    id: 1,
    img: 'https://picsum.photos/2000/1000',
    title: 'Smartphone',
    description: 'Teléfono inteligente con pantalla OLED de 6.5 pulgadas, cámara de 12MP y 256GB de almacenamiento.',
    price: 799.99,
    quantity: 1,
    total: 799.99,
    availability: true,
    isFavorite: false,
    isInCart: false
  },
  {
    id: 2,
    img: 'https://picsum.photos/1000/1000',
    title: 'Laptop',
    description: 'Laptop ultradelgada con procesador Intel Core i7, 16GB de RAM y SSD de 512GB.',
    price: 1299.99,
    quantity: 1,
    total: 1299.99,
    availability: true,
    isFavorite: false,
    isInCart: false  
  },
  {
    id: 3,
    img: 'https://picsum.photos/2000/3000',
    title: 'Smartwatch',
    description: 'Reloj inteligente con monitor de ritmo cardíaco, GPS integrado y resistencia al agua.',
    price: 199.99,
    quantity: 1,
    total: 199.99,
    availability: true,
    isFavorite: false,
    isInCart: false
  },
  {
    id: 4,
    img: 'https://picsum.photos/1000/1200',
    title: 'Auriculares inalámbricos',
    description: 'Auriculares Bluetooth con cancelación de ruido activa y batería de larga duración.',
    price: 149.99,
    quantity: 1,
    total: 149.99,
    availability: true,
    isFavorite: false,
    isInCart: false
  },
  {
    id: 5,
    img: 'https://picsum.photos/1000/1400',
    title: 'Auriculares inalámbricos',
    description: 'Auriculares Bluetooth con cancelación de ruido activa y batería de larga duración.',
    price: 149.99,
    quantity: 1,
    total: 149.99,
    availability: true,
    isFavorite: false,
    isInCart: false
  },
  { id: 6,
    img: 'https://picsum.photos/1300/1200',
    title: 'Auriculares inalámbricos',
    description: 'Auriculares Bluetooth con cancelación de ruido activa y batería de larga duración.',
    price: 149.99,
    quantity: 1,
    total: 149.99,
    availability: true,
    isFavorite: false,
    isInCart: false
  },
  { id: 7,
    img: 'https://picsum.photos/1100/1800',
    title: 'Auriculares inalámbricos',
    description: 'Auriculares Bluetooth con cancelación de ruido activa y batería de larga duración.',
    price: 149.99,
    quantity: 1,
    total: 149.99,
    availability: true,
    isFavorite: false,
    isInCart: false
  },
  {
    id: 8,
    img: 'https://picsum.photos/1600/1500',
    title: 'Auriculares inalámbricos',
    description: 'Auriculares Bluetooth con cancelación de ruido activa y batería de larga duración.',
    price: 149.99,
    quantity: 1,
    total: 149.99,
    availability: true,
    isFavorite: false,
    isInCart: false
  },
  { 
    id: 9,
    img: 'https://picsum.photos/1300/1700',
    title: 'Auriculares inalámbricos',
    description: 'Auriculares Bluetooth con cancelación de ruido activa y batería de larga duración.',
    price: 149.99,
    quantity: 1,
    total: 149.99,
    availability: true,
    isFavorite: false,
    isInCart: false
  },
  { 
    id: 10,
    img: 'https://picsum.photos/1300/1000',
    title: 'Auriculares inalámbricos',
    description: 'Auriculares Bluetooth con cancelación de ruido activa y batería de larga duración.',
    price: 149.99,
    quantity: 1,
    total: 149.99,
    availability: true,
    isFavorite: false,
    isInCart: false
  },
  {
    id: 11,
    img: 'https://picsum.photos/1110/1200',
    title: 'Auriculares inalámbricos',
    description: 'Auriculares Bluetooth con cancelación de ruido activa y batería de larga duración.',
    price: 149.99,
    quantity: 1,
    total: 149.99,
    availability: true,
    isFavorite: false,
    isInCart: false
  }
]
